Гауса

In [5]:
import numpy as np 
def diag(): 
    i = 0 
    j = 0 
    m  = 0 
    for m in range(n): 
        i = 0 
        i += m 
        while i < n: 
            if arr[i][m] != 0: 
                a_ = arr[i][m] 
                 
                while j < n+1: 
                    arr[i][j] = round(arr[i][j]/a_, 3) 
                    j += 1 
                 
                if i >= m+1: 
                    arr[i] -= arr[m] 
            j = 0     
            i += 1 
 
arr = np.array([[ 3.0,  0,  2,  0,  5, -14], 
                [-7,   -3, -2,  3,  2, -14], 
                [ 2,   -1,  3,  4, -4,  -5], 
                [-3,    0, -4,  0, -3,  10], 
                [ 4,    3,  0, -1,  0,   9]]) 
 
n = len(arr[0]) - 1 
 
res = arr.copy() 
 
diag() 
 
i = 0 
j = 0 
m  = 0 
a_ = 0 
while i < n: 
    while j < n-1: 
        if j != n: 
            arr[n-1-j-1-i] -= arr[n-1-i]*arr[n-1-j-1-i][n-1-i]  
        j += 1 
    i += 1 
    j = 0 
 
i = 0 
print(res) 
print() 
while i < n: 
    print(f'x{i+1} = {round(arr[i][5], 3)}') 
    i += 1

[[  3.   0.   2.   0.   5. -14.]
 [ -7.  -3.  -2.   3.   2. -14.]
 [  2.  -1.   3.   4.  -4.  -5.]
 [ -3.   0.  -4.   0.  -3.  10.]
 [  4.   3.   0.  -1.   0.   9.]]

x1 = -0.942
x2 = 3.617
x3 = -0.171
x4 = -1.913
x5 = -2.166


LU-розклад

In [7]:
arr = np.array([[ 3.0,  0,  2,  0,  5], 
                [-7,   -3, -2,  3,  2], 
                [ 2,   -1,  3,  4, -4], 
                [-3,    0, -4,  0, -3], 
                [ 4,    3,  0, -1,  0]]) 
 
      
arr0 = np.array([[1.0, 0, 0, 0, 0], 
                [ 0, 1, 0, 0, 0], 
                [ 0, 0, 1, 0, 0], 
                [ 0, 0, 0, 1, 0], 
                [ 0, 0, 0, 0, 1]]) 
 
 
n = len(arr[0])  
 
q = 0 
 
j = 0 
i = 0 
k = 0 
m = 0 
 
while i < n: 
 
    while j < n-1: 
 
        arr0[j+1][i] += arr0[i][i] * arr[j+1][i]/arr[i][i] 
        arr[j+1] -= arr[i] * arr[j+1][i]/arr[i][i]  
         
        j += 1 
        k += j 
 
    j = 0 
    i += 1 
    j += i 
 
i = 0 
j = 0  
 
while i < n: 
    while j < n: 
        arr0[i][j] = round(arr0[i][j], 3) 
        j += 1 
    j = 0 
    i += 1 
print('U:') 
print(arr) 
print() 
print('L:') 
print(arr0) 
 
print() 
res = np.dot(arr0, arr) 
 
i = 0 
j = 0  
while i < n: 
    while j < n: 
        res[i][j] = round(res[i][j], 2) 
        j += 1 
    j = 0 
    i += 1 

print(f'L*U = A: \n {res}')

U:
[[  3.           0.           2.           0.           5.        ]
 [  0.          -3.           2.66666667   3.          13.66666667]
 [  0.           0.           0.77777778   3.         -11.88888889]
 [  0.           0.           0.           7.71428571 -28.57142857]
 [  0.           0.           0.           0.          14.40740741]]

L:
[[ 1.     0.     0.     0.     0.   ]
 [-2.333  1.     0.     0.     0.   ]
 [ 0.667  0.333  1.     0.     0.   ]
 [-1.     0.    -2.571  1.     0.   ]
 [ 1.333 -1.     0.     0.259  1.   ]]

L*U = A: 
 [[ 3.    0.    2.    0.    5.  ]
 [-7.   -3.   -2.    3.    2.  ]
 [ 2.   -1.    3.    4.   -4.  ]
 [ 4.    3.   -0.   -1.    0.01]
 [-3.    0.   -4.    0.   -3.01]]


Холецького

In [8]:
arr = np.array([[ 3.0,  1,  2,   1], 
                [ 1,    4,  1,  -1], 
                [ 2,    1,  4,   1], 
                [ 1,   -1,  1,   5]]) 
 
arrB = np.array([[1], 
                [-5], 
                [-2], 
                [ 6]]) 
n = len(arr[0])  
arr_ = np.linalg.cholesky(arr) 
i = 0 
j = 0  
while i < n: 
    while j < n: 
        arr[i][j] = round(arr[i][j], 3) 
        j += 1 
    j = 0 
    i += 1 
print('Нижня трикутна матриця:') 
print(arr_) 
print() 
print('Транспонована матриця:') 
tr = arr_.transpose() 
print(tr) 
res = np.dot(arr_, tr) 
print() 
print('Добуток:') 
print(res) 
arr_ # - нижня трикутна 
tr # - транспонована 
# Ly = b 
l = np.concatenate((arr_, arrB), axis=1) 
# print(f'l*y = b : \\n{l}') 
n = len(l[0]) -1 
i = 0 
j = 0 
m  = 0 
for m in range(n): 
    i = 0 
    i += m 
    while i < n: 
        if l[i][m] != 0: 
            a_ = l[i][m] 
             
            while j < n+1: 
                l[i][j] = round(l[i][j]/a_, 3) 
                j += 1 
             
            if i >= m+1: 
                l[i] -= l[m] 
        j = 0     
        i += 1 
y  = [[0], 
      [0],  
      [0], 
      [0]] 
for i in range(4): 
    y[i][0] = l[i][4] 
#Lt*x = y  
lt = np.concatenate((tr, y), axis=1) 
n = len(lt[0]) -1 
i = 0 
j = 0 
while i < n: 
    while j < n-1: 
        a_ = lt[n-j-2][n-i-1] /lt[n-i-1][n-i-1] 
        lt[n-j-2] = lt[n-j-2] - lt[n-i-1] *  a_ 
        j += 1 
    j = 0 
    i += 1 
    j += i 
i = 0 
j = 0  
while i < n: 
    while j < n: 
        lt[i][j] = round(lt[i][j], 3) 
        j += 1 
    j = 0 
    i += 1 
print() 
i = 0 
while i < n: 
    lt[i] = lt[i]/lt[i][i] 
    i += 1 
    print(f'x{i} = {round(lt[i-1][4], 2)}') 

Нижня трикутна матриця:
[[ 1.73205081  0.          0.          0.        ]
 [ 0.57735027  1.91485422  0.          0.        ]
 [ 1.15470054  0.17407766  1.62368828  0.        ]
 [ 0.57735027 -0.69631062  0.27994626  2.02569699]]

Транспонована матриця:
[[ 1.73205081  0.57735027  1.15470054  0.57735027]
 [ 0.          1.91485422  0.17407766 -0.69631062]
 [ 0.          0.          1.62368828  0.27994626]
 [ 0.          0.          0.          2.02569699]]

Добуток:
[[ 3.  1.  2.  1.]
 [ 1.  4.  1. -1.]
 [ 2.  1.  4.  1.]
 [ 1. -1.  1.  5.]]

x1 = 1.0
x2 = -1.0
x3 = -1.0
x4 = 1.0
